<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $files = [
            [
                'filename' => 'user-manual.pdf',
                'original_name' => 'User Manual.pdf',
                'mime_type' => 'application/pdf',
                'size' => 2048576,
                'path' => '/storage/files/user-manual.pdf',
                'url' => 'https://example.com/files/user-manual.pdf',
                'folder' => 'documents',
                'description' => 'Product user manual and instructions',
                'is_public' => true,
                'tags' => json_encode(['manual', 'documentation', 'pdf']),
                'user_id' => 1,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'filename' => 'product-catalog.jpg',
                'original_name' => 'Product Catalog.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 1536000,
                'path' => '/storage/files/product-catalog.jpg',
                'url' => 'https://example.com/files/product-catalog.jpg',
                'folder' => 'images',
                'description' => 'Product catalog image',
                'is_public' => true,
                'tags' => json_encode(['catalog', 'image', 'products']),
                'user_id' => 2,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8),
            ],
            [
                'filename' => 'invoice-001.pdf',
                'original_name' => 'Invoice #001.pdf',
                'mime_type' => 'application/pdf',
                'size' => 512000,
                'path' => '/storage/files/invoice-001.pdf',
                'url' => 'https://example.com/files/invoice-001.pdf',
                'folder' => 'invoices',
                'description' => 'Customer invoice document',
                'is_public' => false,
                'tags' => json_encode(['invoice', 'financial', 'pdf']),
                'user_id' => 3,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'filename' => 'company-logo.png',
                'original_name' => 'Company Logo.png',
                'mime_type' => 'image/png',
                'size' => 256000,
                'path' => '/storage/files/company-logo.png',
                'url' => 'https://example.com/files/company-logo.png',
                'folder' => 'branding',
                'description' => 'Company logo in PNG format',
                'is_public' => true,
                'tags' => json_encode(['logo', 'branding', 'png']),
                'user_id' => 1,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'filename' => 'terms-of-service.docx',
                'original_name' => 'Terms of Service.docx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'size' => 1024000,
                'path' => '/storage/files/terms-of-service.docx',
                'url' => 'https://example.com/files/terms-of-service.docx',
                'folder' => 'legal',
                'description' => 'Terms of service document',
                'is_public' => true,
                'tags' => json_encode(['legal', 'terms', 'document']),
                'user_id' => 1,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'filename' => 'product-demo.mp4',
                'original_name' => 'Product Demo.mp4',
                'mime_type' => 'video/mp4',
                'size' => 52428800,
                'path' => '/storage/files/product-demo.mp4',
                'url' => 'https://example.com/files/product-demo.mp4',
                'folder' => 'videos',
                'description' => 'Product demonstration video',
                'is_public' => true,
                'tags' => json_encode(['demo', 'video', 'product']),
                'user_id' => 2,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'filename' => 'customer-feedback.xlsx',
                'original_name' => 'Customer Feedback.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'size' => 768000,
                'path' => '/storage/files/customer-feedback.xlsx',
                'url' => 'https://example.com/files/customer-feedback.xlsx',
                'folder' => 'reports',
                'description' => 'Customer feedback analysis spreadsheet',
                'is_public' => false,
                'tags' => json_encode(['feedback', 'analysis', 'excel']),
                'user_id' => 3,
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            [
                'filename' => 'banner-ad.jpg',
                'original_name' => 'Banner Ad.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 896000,
                'path' => '/storage/files/banner-ad.jpg',
                'url' => 'https://example.com/files/banner-ad.jpg',
                'folder' => 'marketing',
                'description' => 'Marketing banner advertisement',
                'is_public' => true,
                'tags' => json_encode(['banner', 'marketing', 'advertisement']),
                'user_id' => 2,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'filename' => 'privacy-policy.pdf',
                'original_name' => 'Privacy Policy.pdf',
                'mime_type' => 'application/pdf',
                'size' => 1536000,
                'path' => '/storage/files/privacy-policy.pdf',
                'url' => 'https://example.com/files/privacy-policy.pdf',
                'folder' => 'legal',
                'description' => 'Privacy policy document',
                'is_public' => true,
                'tags' => json_encode(['privacy', 'policy', 'legal']),
                'user_id' => 1,
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'filename' => 'product-specs.txt',
                'original_name' => 'Product Specifications.txt',
                'mime_type' => 'text/plain',
                'size' => 128000,
                'path' => '/storage/files/product-specs.txt',
                'url' => 'https://example.com/files/product-specs.txt',
                'folder' => 'specifications',
                'description' => 'Detailed product specifications',
                'is_public' => true,
                'tags' => json_encode(['specifications', 'technical', 'text']),
                'user_id' => 1,
                'created_at' => now()->subHours(1),
                'updated_at' => now()->subHours(1),
            ],
        ];

        DB::table('files')->insert($files);
    }
}
