<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $notifications = [
            [
                'user_id' => 2,
                'type' => 'email',
                'subject' => 'Welcome to our platform!',
                'message' => 'Thank you for joining our platform. We\'re excited to have you on board!',
                'priority' => 'medium',
                'status' => 'sent',
                'scheduled_at' => null,
                'sent_at' => now()->subDays(10),
                'read_at' => now()->subDays(9),
                'template_id' => 1,
                'variables' => json_encode(['site_name' => 'Nimbus Store', 'user_name' => 'Jane Smith']),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(9),
            ],
            [
                'user_id' => 2,
                'type' => 'email',
                'subject' => 'Order Confirmation - #1',
                'message' => 'Thank you for your order! We\'ve received your order #1 and it\'s being processed.',
                'priority' => 'high',
                'status' => 'sent',
                'scheduled_at' => null,
                'sent_at' => now()->subDays(5),
                'read_at' => now()->subDays(4),
                'template_id' => 2,
                'variables' => json_encode([
                    'user_name' => 'Jane Smith',
                    'order_number' => '1',
                    'order_items' => 'Wireless Bluetooth Headphones',
                    'order_total' => '219.99',
                    'site_name' => 'Nimbus Store',
                ]),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(4),
            ],
            [
                'user_id' => 2,
                'type' => 'email',
                'subject' => 'Your Order Has Shipped - #1',
                'message' => 'Great news! Your order #1 has been shipped. Tracking Number: TRK123456789',
                'priority' => 'high',
                'status' => 'sent',
                'scheduled_at' => null,
                'sent_at' => now()->subDays(3),
                'read_at' => now()->subDays(2),
                'template_id' => 3,
                'variables' => json_encode([
                    'user_name' => 'Jane Smith',
                    'order_number' => '1',
                    'tracking_number' => 'TRK123456789',
                    'shipping_method' => 'standard',
                ]),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => 3,
                'type' => 'push',
                'subject' => 'New Product Alert',
                'message' => 'Check out our latest product: Smart Watch Series 8! Only $399.99',
                'priority' => 'medium',
                'status' => 'sent',
                'scheduled_at' => null,
                'sent_at' => now()->subDays(2),
                'read_at' => now()->subDays(1),
                'template_id' => 5,
                'variables' => json_encode([
                    'product_name' => 'Smart Watch Series 8',
                    'product_price' => '399.99',
                ]),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(1),
            ],
            [
                'user_id' => 6,
                'type' => 'sms',
                'subject' => 'Order Update',
                'message' => 'Your order #3 status: shipped. Track: https://tracking.example.com/TRK987654321',
                'priority' => 'high',
                'status' => 'sent',
                'scheduled_at' => null,
                'sent_at' => now()->subDays(1),
                'read_at' => now()->subHours(12),
                'template_id' => 6,
                'variables' => json_encode([
                    'order_number' => '3',
                    'order_status' => 'shipped',
                    'tracking_link' => 'https://tracking.example.com/TRK987654321',
                ]),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subHours(12),
            ],
            [
                'user_id' => 4,
                'type' => 'in_app',
                'subject' => 'Account Verification',
                'message' => 'Please verify your email address to access all features.',
                'priority' => 'urgent',
                'status' => 'pending',
                'scheduled_at' => null,
                'sent_at' => null,
                'read_at' => null,
                'template_id' => 7,
                'variables' => json_encode([]),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'type' => 'email',
                'subject' => 'Password Reset Request',
                'message' => 'You requested a password reset for your Nimbus Store account.',
                'priority' => 'high',
                'status' => 'failed',
                'scheduled_at' => null,
                'sent_at' => null,
                'read_at' => null,
                'template_id' => 4,
                'variables' => json_encode([
                    'user_name' => 'Robert Miller',
                    'site_name' => 'Nimbus Store',
                    'reset_link' => 'https://example.com/reset/token123',
                    'expiry_hours' => '24',
                ]),
                'attachments' => null,
                'error_message' => 'SMTP server connection timeout',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(1),
            ],
            [
                'user_id' => 8,
                'type' => 'email',
                'subject' => 'Weekly Newsletter - 2024-01-15',
                'message' => 'Here\'s what\'s new this week: New products, special deals, and more!',
                'priority' => 'low',
                'status' => 'sent',
                'scheduled_at' => now()->subDays(1),
                'sent_at' => now()->subDays(1),
                'read_at' => null,
                'template_id' => 8,
                'variables' => json_encode([
                    'user_name' => 'Lisa Garcia',
                    'week_date' => '2024-01-15',
                    'newsletter_content' => 'New products, special deals, and more!',
                    'site_name' => 'Nimbus Store',
                ]),
                'attachments' => null,
                'error_message' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(1),
            ],
        ];

        DB::table('notifications')->insert($notifications);
    }
}
