<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orders = [
            [
                'user_id' => 2,
                'status' => 'delivered',
                'subtotal' => 199.99,
                'tax' => 20.00,
                'shipping' => 0.00,
                'total' => 219.99,
                'shipping_address' => json_encode([
                    'name' => 'Jane Smith',
                    'street' => '123 Main Street',
                    'city' => 'New York',
                    'state' => 'NY',
                    'postal_code' => '10001',
                    'country' => 'US',
                ]),
                'billing_address' => json_encode([
                    'name' => 'Jane Smith',
                    'street' => '123 Main Street',
                    'city' => 'New York',
                    'state' => 'NY',
                    'postal_code' => '10001',
                    'country' => 'US',
                ]),
                'payment_method' => 'credit_card',
                'payment_details' => json_encode([
                    'card_type' => 'Visa',
                    'last_four' => '1234',
                    'expiry_month' => 12,
                    'expiry_year' => 2025,
                ]),
                'shipping_method' => 'standard',
                'notes' => 'Please leave package at front door if no answer.',
                'coupon_code' => null,
                'gift_message' => null,
                'tracking_number' => 'TRK123456789',
                'shipped_at' => now()->subDays(3),
                'delivered_at' => now()->subDays(1),
                'cancelled_at' => null,
                'cancellation_reason' => null,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(1),
            ],
            [
                'user_id' => 3,
                'status' => 'processing',
                'subtotal' => 549.98,
                'tax' => 55.00,
                'shipping' => 15.00,
                'total' => 619.98,
                'shipping_address' => json_encode([
                    'name' => 'Mike Johnson',
                    'street' => '456 Oak Avenue',
                    'city' => 'Los Angeles',
                    'state' => 'CA',
                    'postal_code' => '90210',
                    'country' => 'US',
                ]),
                'billing_address' => json_encode([
                    'name' => 'Mike Johnson',
                    'street' => '456 Oak Avenue',
                    'city' => 'Los Angeles',
                    'state' => 'CA',
                    'postal_code' => '90210',
                    'country' => 'US',
                ]),
                'payment_method' => 'paypal',
                'payment_details' => json_encode([
                    'paypal_email' => 'mike.johnson@example.com',
                    'transaction_id' => 'PP123456789',
                ]),
                'shipping_method' => 'express',
                'notes' => 'Gift wrapping requested.',
                'coupon_code' => 'SAVE10',
                'gift_message' => 'Happy Birthday! Enjoy your new gadgets.',
                'tracking_number' => null,
                'shipped_at' => null,
                'delivered_at' => null,
                'cancelled_at' => null,
                'cancellation_reason' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'status' => 'shipped',
                'subtotal' => 89.99,
                'tax' => 9.00,
                'shipping' => 8.99,
                'total' => 107.98,
                'shipping_address' => json_encode([
                    'name' => 'Emily Davis',
                    'street' => '789 Pine Street',
                    'city' => 'Chicago',
                    'state' => 'IL',
                    'postal_code' => '60601',
                    'country' => 'US',
                ]),
                'billing_address' => null,
                'payment_method' => 'debit_card',
                'payment_details' => json_encode([
                    'card_type' => 'Mastercard',
                    'last_four' => '5678',
                    'expiry_month' => 8,
                    'expiry_year' => 2026,
                ]),
                'shipping_method' => 'standard',
                'notes' => null,
                'coupon_code' => null,
                'gift_message' => null,
                'tracking_number' => 'TRK987654321',
                'shipped_at' => now()->subDays(1),
                'delivered_at' => null,
                'cancelled_at' => null,
                'cancellation_reason' => null,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(1),
            ],
            [
                'user_id' => 7,
                'status' => 'pending',
                'subtotal' => 29.99,
                'tax' => 3.00,
                'shipping' => 5.99,
                'total' => 38.98,
                'shipping_address' => json_encode([
                    'name' => 'Robert Miller',
                    'street' => '321 Elm Street',
                    'city' => 'Houston',
                    'state' => 'TX',
                    'postal_code' => '77001',
                    'country' => 'US',
                ]),
                'billing_address' => null,
                'payment_method' => 'bank_transfer',
                'payment_details' => json_encode([
                    'bank_name' => 'First National Bank',
                    'account_last_four' => '9876',
                    'routing_number' => '123456789',
                ]),
                'shipping_method' => 'standard',
                'notes' => 'Please call before delivery.',
                'coupon_code' => null,
                'gift_message' => null,
                'tracking_number' => null,
                'shipped_at' => null,
                'delivered_at' => null,
                'cancelled_at' => null,
                'cancellation_reason' => null,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'user_id' => 8,
                'status' => 'cancelled',
                'subtotal' => 299.99,
                'tax' => 30.00,
                'shipping' => 0.00,
                'total' => 329.99,
                'shipping_address' => json_encode([
                    'name' => 'Lisa Garcia',
                    'street' => '654 Maple Drive',
                    'city' => 'Phoenix',
                    'state' => 'AZ',
                    'postal_code' => '85001',
                    'country' => 'US',
                ]),
                'billing_address' => null,
                'payment_method' => 'credit_card',
                'payment_details' => json_encode([
                    'card_type' => 'American Express',
                    'last_four' => '9012',
                    'expiry_month' => 6,
                    'expiry_year' => 2025,
                ]),
                'shipping_method' => 'overnight',
                'notes' => null,
                'coupon_code' => null,
                'gift_message' => null,
                'tracking_number' => null,
                'shipped_at' => null,
                'delivered_at' => null,
                'cancelled_at' => now()->subDays(1),
                'cancellation_reason' => 'Customer requested cancellation due to change of mind.',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(1),
            ],
        ];

        DB::table('orders')->insert($orders);

        $orderItems = [
            [
                'order_id' => 1,
                'product_id' => 1,
                'product_name' => 'Wireless Bluetooth Headphones',
                'price' => 199.99,
                'quantity' => 1,
                'total' => 199.99,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'order_id' => 2,
                'product_id' => 2,
                'product_name' => 'Smart Watch Series 8',
                'price' => 399.99,
                'quantity' => 1,
                'total' => 399.99,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'order_id' => 2,
                'product_id' => 3,
                'product_name' => 'Gaming Mechanical Keyboard',
                'price' => 149.99,
                'quantity' => 1,
                'total' => 149.99,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'order_id' => 3,
                'product_id' => 8,
                'product_name' => 'Bluetooth Speaker',
                'price' => 89.99,
                'quantity' => 1,
                'total' => 89.99,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'order_id' => 4,
                'product_id' => 6,
                'product_name' => 'Premium Cotton T-Shirt',
                'price' => 29.99,
                'quantity' => 1,
                'total' => 29.99,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'order_id' => 5,
                'product_id' => 7,
                'product_name' => 'Modern Office Chair',
                'price' => 299.99,
                'quantity' => 1,
                'total' => 299.99,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
        ];

        DB::table('order_items')->insert($orderItems);
    }
}
