<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $images = [
            [
                'product_id' => 1,
                'filename' => 'wireless-headphones-main.jpg',
                'original_name' => 'wireless-headphones-main.jpg',
                'path' => '/storage/products/wireless-headphones-main.jpg',
                'url' => 'https://example.com/images/products/wireless-headphones-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 245760,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'filename' => 'wireless-headphones-side.jpg',
                'original_name' => 'wireless-headphones-side.jpg',
                'path' => '/storage/products/wireless-headphones-side.jpg',
                'url' => 'https://example.com/images/products/wireless-headphones-side.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 198432,
                'sort_order' => 1,
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'filename' => 'smartwatch-main.jpg',
                'original_name' => 'smartwatch-main.jpg',
                'path' => '/storage/products/smartwatch-main.jpg',
                'url' => 'https://example.com/images/products/smartwatch-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 312456,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'filename' => 'smartwatch-strap.jpg',
                'original_name' => 'smartwatch-strap.jpg',
                'path' => '/storage/products/smartwatch-strap.jpg',
                'url' => 'https://example.com/images/products/smartwatch-strap.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 187654,
                'sort_order' => 1,
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'filename' => 'gaming-keyboard-main.jpg',
                'original_name' => 'gaming-keyboard-main.jpg',
                'path' => '/storage/products/gaming-keyboard-main.jpg',
                'url' => 'https://example.com/images/products/gaming-keyboard-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 456789,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'filename' => 'charging-pad-main.jpg',
                'original_name' => 'charging-pad-main.jpg',
                'path' => '/storage/products/charging-pad-main.jpg',
                'url' => 'https://example.com/images/products/charging-pad-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 123456,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'filename' => 'cotton-tshirt-main.jpg',
                'original_name' => 'cotton-tshirt-main.jpg',
                'path' => '/storage/products/cotton-tshirt-main.jpg',
                'url' => 'https://example.com/images/products/cotton-tshirt-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 98765,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'filename' => 'cotton-tshirt-back.jpg',
                'original_name' => 'cotton-tshirt-back.jpg',
                'path' => '/storage/products/cotton-tshirt-back.jpg',
                'url' => 'https://example.com/images/products/cotton-tshirt-back.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 87654,
                'sort_order' => 1,
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'filename' => 'office-chair-main.jpg',
                'original_name' => 'office-chair-main.jpg',
                'path' => '/storage/products/office-chair-main.jpg',
                'url' => 'https://example.com/images/products/office-chair-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 567890,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'filename' => 'office-chair-side.jpg',
                'original_name' => 'office-chair-side.jpg',
                'path' => '/storage/products/office-chair-side.jpg',
                'url' => 'https://example.com/images/products/office-chair-side.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 456789,
                'sort_order' => 1,
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'filename' => 'bluetooth-speaker-main.jpg',
                'original_name' => 'bluetooth-speaker-main.jpg',
                'path' => '/storage/products/bluetooth-speaker-main.jpg',
                'url' => 'https://example.com/images/products/bluetooth-speaker-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 234567,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'filename' => 'designer-handbag-main.jpg',
                'original_name' => 'designer-handbag-main.jpg',
                'path' => '/storage/products/designer-handbag-main.jpg',
                'url' => 'https://example.com/images/products/designer-handbag-main.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 345678,
                'sort_order' => 0,
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'filename' => 'designer-handbag-interior.jpg',
                'original_name' => 'designer-handbag-interior.jpg',
                'path' => '/storage/products/designer-handbag-interior.jpg',
                'url' => 'https://example.com/images/products/designer-handbag-interior.jpg',
                'mime_type' => 'image/jpeg',
                'size' => 298765,
                'sort_order' => 1,
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('product_images')->insert($images);
    }
}
