<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Wireless Bluetooth Headphones',
                'description' => 'High-quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.',
                'price' => 199.99,
                'category_id' => 2,
                'status' => 'active',
                'stock_quantity' => 50,
                'sku' => 'WBH-001',
                'weight' => 0.25,
                'length' => 20.0,
                'width' => 18.0,
                'height' => 8.0,
                'specifications' => json_encode([
                    'battery_life' => '30 hours',
                    'connectivity' => 'Bluetooth 5.0',
                    'noise_cancellation' => 'Active',
                    'driver_size' => '40mm',
                    'frequency_response' => '20Hz - 20kHz',
                ]),
                'tags' => json_encode(['wireless', 'bluetooth', 'noise-cancellation', 'premium']),
                'is_featured' => true,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Wireless Bluetooth Headphones - Premium Audio',
                'seo_description' => 'High-quality wireless headphones with noise cancellation',
                'seo_keywords' => 'wireless headphones, bluetooth, noise cancellation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smart Watch Series 8',
                'description' => 'Advanced smartwatch with health monitoring, GPS, and water resistance. Track your fitness and stay connected.',
                'price' => 399.99,
                'category_id' => 4,
                'status' => 'active',
                'stock_quantity' => 25,
                'sku' => 'SW-008',
                'weight' => 0.05,
                'length' => 4.4,
                'width' => 3.8,
                'height' => 1.0,
                'specifications' => json_encode([
                    'display' => '1.9" OLED',
                    'battery_life' => '18 hours',
                    'water_resistance' => '50m',
                    'gps' => 'Built-in',
                    'health_features' => 'Heart rate, Sleep tracking, ECG',
                ]),
                'tags' => json_encode(['smartwatch', 'fitness', 'health', 'gps']),
                'is_featured' => true,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Smart Watch Series 8 - Health & Fitness',
                'seo_description' => 'Advanced smartwatch with health monitoring and GPS',
                'seo_keywords' => 'smartwatch, fitness, health monitoring, gps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gaming Mechanical Keyboard',
                'description' => 'RGB mechanical keyboard with customizable keys and tactile switches. Perfect for gaming and programming.',
                'price' => 149.99,
                'category_id' => 3,
                'status' => 'active',
                'stock_quantity' => 30,
                'sku' => 'GMK-001',
                'weight' => 1.2,
                'length' => 45.0,
                'width' => 15.0,
                'height' => 3.5,
                'specifications' => json_encode([
                    'switch_type' => 'Cherry MX Blue',
                    'backlight' => 'RGB',
                    'connectivity' => 'USB-C',
                    'key_layout' => 'Full-size',
                    'durability' => '50 million keystrokes',
                ]),
                'tags' => json_encode(['gaming', 'mechanical', 'rgb', 'keyboard']),
                'is_featured' => false,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Gaming Mechanical Keyboard - RGB',
                'seo_description' => 'RGB mechanical keyboard for gaming and programming',
                'seo_keywords' => 'gaming keyboard, mechanical, rgb, cherry mx',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wireless Charging Pad',
                'description' => 'Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator.',
                'price' => 49.99,
                'category_id' => 1,
                'status' => 'active',
                'stock_quantity' => 75,
                'sku' => 'WCP-001',
                'weight' => 0.3,
                'length' => 10.0,
                'width' => 10.0,
                'height' => 1.0,
                'specifications' => json_encode([
                    'charging_speed' => '15W',
                    'compatibility' => 'Qi-enabled devices',
                    'led_indicator' => 'Yes',
                    'cable_length' => '1.5m',
                    'safety_features' => 'Overcharge protection',
                ]),
                'tags' => json_encode(['wireless', 'charging', 'qi', 'fast-charge']),
                'is_featured' => false,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Wireless Charging Pad - Fast Charge',
                'seo_description' => 'Fast wireless charging pad for Qi-enabled devices',
                'seo_keywords' => 'wireless charging, qi, fast charge, charging pad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Photography Course',
                'description' => 'Complete online course covering digital photography fundamentals, composition, and post-processing techniques.',
                'price' => 79.99,
                'category_id' => 10,
                'status' => 'active',
                'stock_quantity' => 999,
                'sku' => 'DPC-001',
                'weight' => null,
                'length' => null,
                'width' => null,
                'height' => null,
                'specifications' => json_encode([
                    'duration' => '20 hours',
                    'lessons' => '45 lessons',
                    'level' => 'Beginner to Intermediate',
                    'certificate' => 'Yes',
                    'lifetime_access' => 'Yes',
                ]),
                'tags' => json_encode(['photography', 'course', 'digital', 'online']),
                'is_featured' => true,
                'is_digital' => true,
                'download_url' => 'https://example.com/courses/photography',
                'seo_title' => 'Digital Photography Course - Online Learning',
                'seo_description' => 'Complete online course for digital photography',
                'seo_keywords' => 'photography course, digital photography, online learning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Premium Cotton T-Shirt',
                'description' => 'Soft, comfortable cotton t-shirt made from 100% organic cotton. Available in multiple colors and sizes.',
                'price' => 29.99,
                'category_id' => 6,
                'status' => 'active',
                'stock_quantity' => 100,
                'sku' => 'PCT-001',
                'weight' => 0.2,
                'length' => 70.0,
                'width' => 50.0,
                'height' => 1.0,
                'specifications' => json_encode([
                    'material' => '100% Organic Cotton',
                    'care_instructions' => 'Machine wash cold',
                    'fit' => 'Regular',
                    'origin' => 'Made in USA',
                    'certifications' => 'GOTS Certified',
                ]),
                'tags' => json_encode(['cotton', 'organic', 't-shirt', 'premium']),
                'is_featured' => false,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Premium Cotton T-Shirt - Organic',
                'seo_description' => 'Soft organic cotton t-shirt in multiple colors',
                'seo_keywords' => 'cotton t-shirt, organic, premium, comfortable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Modern Office Chair',
                'description' => 'Ergonomic office chair with lumbar support, adjustable height, and breathable mesh back. Perfect for long work sessions.',
                'price' => 299.99,
                'category_id' => 9,
                'status' => 'active',
                'stock_quantity' => 15,
                'sku' => 'MOC-001',
                'weight' => 15.0,
                'length' => 60.0,
                'width' => 60.0,
                'height' => 120.0,
                'specifications' => json_encode([
                    'material' => 'Mesh and Plastic',
                    'weight_capacity' => '300 lbs',
                    'adjustable_height' => 'Yes',
                    'lumbar_support' => 'Yes',
                    'warranty' => '5 years',
                ]),
                'tags' => json_encode(['office', 'chair', 'ergonomic', 'mesh']),
                'is_featured' => true,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Modern Office Chair - Ergonomic',
                'seo_description' => 'Ergonomic office chair with lumbar support',
                'seo_keywords' => 'office chair, ergonomic, lumbar support, mesh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bluetooth Speaker',
                'description' => 'Portable Bluetooth speaker with 360-degree sound, waterproof design, and 12-hour battery life.',
                'price' => 89.99,
                'category_id' => 2,
                'status' => 'active',
                'stock_quantity' => 40,
                'sku' => 'BTS-001',
                'weight' => 0.6,
                'length' => 18.0,
                'width' => 7.0,
                'height' => 7.0,
                'specifications' => json_encode([
                    'battery_life' => '12 hours',
                    'waterproof' => 'IPX7',
                    'connectivity' => 'Bluetooth 5.0',
                    'range' => '30 feet',
                    'speaker_drivers' => '2 x 2.5"',
                ]),
                'tags' => json_encode(['bluetooth', 'speaker', 'portable', 'waterproof']),
                'is_featured' => false,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Bluetooth Speaker - Portable & Waterproof',
                'seo_description' => 'Portable Bluetooth speaker with waterproof design',
                'seo_keywords' => 'bluetooth speaker, portable, waterproof, 360 sound',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Programming Fundamentals E-book',
                'description' => 'Comprehensive e-book covering programming fundamentals, algorithms, and best practices for beginners.',
                'price' => 39.99,
                'category_id' => 10,
                'status' => 'active',
                'stock_quantity' => 999,
                'sku' => 'PFE-001',
                'weight' => null,
                'length' => null,
                'width' => null,
                'height' => null,
                'specifications' => json_encode([
                    'pages' => '450 pages',
                    'format' => 'PDF, EPUB, MOBI',
                    'languages' => 'Multiple programming languages',
                    'level' => 'Beginner',
                    'updates' => 'Free lifetime updates',
                ]),
                'tags' => json_encode(['programming', 'ebook', 'fundamentals', 'algorithms']),
                'is_featured' => false,
                'is_digital' => true,
                'download_url' => 'https://example.com/ebooks/programming-fundamentals',
                'seo_title' => 'Programming Fundamentals E-book',
                'seo_description' => 'Comprehensive programming fundamentals e-book',
                'seo_keywords' => 'programming ebook, fundamentals, algorithms, coding',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Designer Handbag',
                'description' => 'Elegant designer handbag made from premium leather with multiple compartments and adjustable strap.',
                'price' => 199.99,
                'category_id' => 7,
                'status' => 'active',
                'stock_quantity' => 20,
                'sku' => 'DHB-001',
                'weight' => 0.8,
                'length' => 30.0,
                'width' => 20.0,
                'height' => 15.0,
                'specifications' => json_encode([
                    'material' => 'Premium Leather',
                    'compartments' => '3 main + 2 side',
                    'strap_type' => 'Adjustable',
                    'closure' => 'Magnetic snap',
                    'care' => 'Leather conditioner recommended',
                ]),
                'tags' => json_encode(['handbag', 'designer', 'leather', 'elegant']),
                'is_featured' => true,
                'is_digital' => false,
                'download_url' => null,
                'seo_title' => 'Designer Handbag - Premium Leather',
                'seo_description' => 'Elegant designer handbag in premium leather',
                'seo_keywords' => 'designer handbag, leather, elegant, premium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
